# Site settings
title: Dorian Hall
email: dorianleehall@gmail.com
description: Programmer and Designer
url: https://dorian_hall.github.io
linkedin_url: https://www.linkedin.com/in/dorian-hall-020b6a289/
twitter_username: https://twitter.com/The_0tz
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
